site_name: pytzer
site_author: Matthew P. Humphreys
site_description: Pitzer model for chemical speciation
copyright: Copyright &copy; 2019 Matthew Paul Humphreys under the GNU GPLv3.
repo_url: https://github.com/mvdh7/pytzer

theme:
    name: readthedocs

nav:
    - Overview: index.md
    - Modules:
        - Import and export: modules/io.md
        - Coefficient dictionaries: modules/coefficient-dictionaries.md
        - Pitzer model implementation: modules/pitzer-model-implementation.md
        - Interaction coefficients: modules/interaction-coefficients.md
        - Unsymmetrical mixing: modules/unsymmetrical-mixing.md
        - Universal ionic properties: modules/universal-ionic-properties.md
        - Physical constants: modules/physical-constants.md
