site_name: pytzer
site_author: Matthew P. Humphreys
theme: readthedocs
nav:
- Overview: index.md
- Import and export: io.md
- Coefficient dictionaries: cfdicts.md
- The Pitzer model: model.md
- Interaction coefficients: coeffs.md
- Unsymmetrical mixing: jfuncs.md
- Universal ionic properties: props.md
- Physical constants: constants.md
