site_name: Pytzer
site_author: Matthew P. Humphreys
site_description: Pitzer model for chemical activities in aqueous solutions
copyright: Copyright &copy; 2019-2020 Matthew P. Humphreys (GNU GPLv3).
repo_url: https://github.com/mvdh7/pytzer
repo_name: mvdh7/pytzer

theme:
  name: material
  language: en
  palette:
    primary: pink
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Overview: index.md
  - Quick-start guide: quick-start.md
  - Example workflows: workflows.md
  - Conventions: name-conventions.md
  - Main Pytzer modules:
    - .io – import and export data: modules/io.md
    - .model – the Pitzer model: modules/model.md
    - .equilibrate - equilibrium solvers: modules/equilibrate.md
  - Behind the scenes:
    - .libraries – parameter libraries: modules/libraries.md
    - .parameters – interaction parameter functions: modules/parameters.md
    - .tables - parameter tables: modules/tables.md
    - .debyehueckel – Debye-Hückel limiting slopes: modules/debyehueckel.md
    - .unsymmetrical – unsymmetrical mixing terms: modules/unsymmetrical.md
    - .properties – solute properties: modules/properties.md
    - .constants – physical constants: modules/constants.md
    - .teos10 - TEOS-10 properties: modules/teos10.md
    - .matrix - matrix model: modules/matrix.md
    - .dissociation - thermodynamic equilibrium constants: modules/dissociation.md
    - .potentials - standard chemical potentials: module/potentials.md
    - .meta - package metadata: modules/meta.md
  - References: references.md
  - Version history: version-history.md

markdown_extensions:
  - admonition
