site_name: pytzer
site_author: Matthew P. Humphreys
site_description: Pitzer model for chemical speciation
copyright: Copyright &copy; 2019 Matthew P. Humphreys (GNU GPLv3).
repo_url: https://github.com/mvdh7/pytzer

theme:
    name: readthedocs

nav:
    - Overview: index.md
    - Conventions: name-conventions.md
    - pytzer modules:
        - .io – import and export:             modules/io.md
        - .cfdicts – coefficient dictionaries: modules/cfdicts.md
        - .model – the Pitzer model:           modules/model.md
        - .coeffs – interaction coefficients:  modules/coeffs.md
        - .jfuncs – unsymmetrical mixing:      modules/jfuncs.md
        - .props – universal ionic properties: modules/props.md
        - .constants – physical constants:     modules/constants.md
        - .meta - package metadata:            modules/meta.md
    - Version history: version-history.md
